stuff

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -159,11 +159,12 @@ runs:
 
         mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && chmod -R g=,o= ~/.ssh
         echo "${{ inputs.ssh_known_hosts }}" > ~/.ssh/known_hosts
+        if [ ! grep -q ${RSYNC_SERVER} ~/.ssh/known_hosts ]; then echo "[ERROR] ${RSYNC_SERVER} is not in ~/.ssh/known_hosts" ; exit 1 ; fi
 
         eval $(ssh-agent -s)
         echo '${{ inputs.ssh_secret_key }}' | ssh-add -
         
-        set | grep RSYNC
+        #set | grep RSYNC
         set -x
         rsync ${RSYNC_ARGS} ./public/* "${RSYNC_USER}@${RSYNC_SERVER}:${RSYNC_DEST_DIR}"
         #if [ "${FORGEJO_EVENT_NAME}" == "pull_request" ] ; then
